// <auto-generated />
using System;
using Assurances.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assurances.API.Migrations
{
    [DbContext(typeof(AssurancesContext))]
    partial class AssurancesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Assurances.API.Models.ContratAssurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodePartenaire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstDiabetique")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstFumeur")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstHypertendu")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstPhysiquementActif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdClient")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomDemandeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SexeDemandeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContratAssurances");
                });
#pragma warning restore 612, 618
        }
    }
}
